### Task 2.1 GET All Students
GET http://localhost:5100/api/students
Content-Type: application/json


### Task 2.2 GET Students by Major (Query String)
GET http://localhost:5100/api/students?major=Mathematics
Content-Type: application/json


### Task 2.3 GET Single Student by ID
GET http://localhost:5100/api/students/1
Content-Type: application/json


### Task 2.3 Test Error - Student Not Found
GET http://localhost:5100/api/students/5
Content-Type: application/json